name: CI
run-name: ${{ github.workflow }} started by @${{ github.triggering_actor}}
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
