name: CI

on:
  push: 
    branches:
      - main
    tags: 
      - v*
  pull_request:
    types: 
        - closed
        - opened
        - synchronize

jobs:
  main:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish artifact
        uses: dummyorg-mondo192/artifactory-publish@main
        with:
          jf-env-mondo192: ${{ secrets.JF_SECRET_ENV_MONDO192 }}
          repository-type: "npm"
